apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bitwarden-rs
  name: bitwarden-rs
  namespace: bitwarden
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    io.kompose.service: bitwarden-rs
  type: LoadBalancer
