apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bitwarden-rs
  name: bitwarden-rs
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bitwarden-rs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Paul-ChristiaanDiks\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-default: "true"
        io.kompose.service: bitwarden-rs
    spec:
      containers:
        - env:
            - name: ADMIN_TOKEN
              value: Erwaseenseenrijkekoopman!
            - name: SIGNUPS_ALLOWED
              value: "false"
          image: vaultwarden/server:latest
          imagePullPolicy: Always
          name: bitwarden-rs
          ports:
            - containerPort: 80
              hostPort: 85
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: bitwarden-rs-claim0
      restartPolicy: Always
      volumes:
        - name: bitwarden-rs-claim0
          persistentVolumeClaim:
            claimName: bitwarden-rs-pvc
