apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: bitwarden-rs-pvc
  name: bitwarden-rs-pvc
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
