apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bitwarden-rs-pvc
  name: bitwarden-rs-pvc
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-ac2a1d18-e9f8-4bc4-b259-dd20197519c0
status: {}
