apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
  labels:
    app: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
      tier: adguard
  template:
    metadata:
      labels:
        app: adguard
        tier: adguard
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        imagePullPolicy: Always
#        env:
#        - name: AGH_CONFIG
#          valueFrom:
#            configMapKeyRef:
#              name: adguard-homeconfig
#              key: AdGuardHome.yaml
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 3000
          name: http-initial
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: adguard-work
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-work-pvc
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-conf-pvc
