apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-homeconfig
  namespace: adguard
data:
  AdGuardHome.yaml: |
    http:
      pprof:
        port: 6060
        enabled: false
      address: 0.0.0.0:80
      session_ttl: 720h
