apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: unifi-claim0
  name: unifi-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
