apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Paul-ChristiaanDiks\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: unifi
  name: unifi
  namespace: unifi
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-device
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: device-https
      port: 8443
      targetPort: 8443
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
  selector:
    io.kompose.service: unifi
  type: LoadBalancer
status:
  loadBalancer: {}
